config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: { omniauth_callbacks: 'admin/omniauth_callbacks' }
  devise_scope :admin_user do
    get 'admin/sign_in', to: 'admin/sessions#new', as: :new_admin_user_session
    get 'admin/sign_out', to: 'admin/sessions#destroy', as: :destroy_admin_user_session
  end
  namespace :admin do
    resources :cases, only: [:index, :show, :destroy]  do
      resources :messages, only: [:create, :edit, :update]
    end
    resources :intakes, only: [:index, :show]
  end

  resources :intakes, only: [:new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#index"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/case.rb
class Admin::Case < ApplicationRecord
  include AASM

  aasm do
    state :open, initial: true
    state :reviewed, :responded, :closed

    event :review do
      transitions from: :open, to: :reviewed
      transitions from: :reviewed, to: :reviewed
    end

    event :respond do
      transitions from: :reviewed, to: :responded
      transitions from: :responded, to: :responded
    end

    event :close do
      transitions from: :reviewed, to: :closed
      transitions from: :responded, to: :closed
    end
  end

  belongs_to :intake
  has_many :messages, -> { order  'created_at desc' }

  before_create :generate_token

  private

  def generate_token
    self.token = SecureRandom.urlsafe_base64(10)
  end
end

app/models/admin/message.rb
class Admin::Message < ApplicationRecord
  enum direction: %i[internal in out]
  has_rich_text :body
  belongs_to :case

  def sender
    return 'internal note' if internal?
    return self.case.intake.name if in?
    return 'admin user' if out?
  end

  private

  def editable?
    internal?
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :validatable,
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@flagrant.dev\z/
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url)
      .find_or_create_by!(email: email)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/intake.rb
class Intake < ApplicationRecord
  has_one :case, class_name: "Admin::Case"

  after_create :ensure_case

  def sender
    "#{name} (#{email})"
  end

  private

  def ensure_case
    Admin::Case.find_or_create_by!(intake_id: id)
  end
end

app/controllers/admin/cases_controller.rb
class Admin::CasesController < AdminController
  before_action :set_admin_case, only: [:show, :edit, :update, :destroy]

  # GET /admin/cases
  # GET /admin/cases.json
  def index
    @admin_cases = Admin::Case.where.not(aasm_state: 'closed')
  end

  def show
    @admin_case.review! if @admin_case.open?
  end

  def destroy
    @admin_case.close!
    respond_to do |format|
      format.html { redirect_to admin_cases_url, notice: 'Case closed!' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_case
    @admin_case = Admin::Case.find(params[:id])
  end

  def admin_case_params
    params.fetch(:admin_case, {})
  end
end

app/controllers/admin/intakes_controller.rb
class Admin::IntakesController < ApplicationController
  before_action :set_intake, only: [:show]

  # GET /intakes
  # GET /intakes.json
  def index
    @intakes = Intake.all
  end

  # GET /intakes/1
  # GET /intakes/1.json
  def show; end

  private

  def set_intake
    @intake = Intake.find(params[:id])
  end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < AdminController
  before_action :set_admin_case
  before_action :set_message, only: [:edit, :update]

  def edit; end

  def create
    @admin_message = @admin_case.messages.new(message_params)
    respond_to do |format|
      if @admin_message.save
        if @admin_message.out?
          @admin_case.respond!
          Admin::CaseMessageMailer.with(kase: @admin_case, message: @admin_message)
            .message_email.deliver_later
        end

        format.html { redirect_to @admin_case, notice: 'Message was successfully added.' }
        # format.json { render :show, status: :ok, location: @admin_case }
      else
        format.html { render :edit }
        # format.json { render json: @admin_case.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # TODO: messages are not editable unless they are internal
    respond_to do |format|
      if @admin_message.update(message_params)
        format.html { redirect_to @admin_case, notice: 'Message was successfully updated.' }
        # format.json { render :show, status: :ok, location: @admin_case }
      else
        format.html { render :edit }
        # format.json { render json: @admin_case.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_admin_case
    @admin_case = Admin::Case.find(params[:case_id])
  end

  def set_message
    @admin_message = Admin::Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:admin_message).permit(:body, :case_id, :direction)
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    admin = AdminUser.from_google(from_google_params)

    if admin.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect admin, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_admin_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_admin_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource_or_scope)
    new_admin_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/intakes_controller.rb
class IntakesController < ApplicationController
  before_action :set_intake, only: [:show]

  # GET /intakes
  # GET /intakes.json
  def index
    @intakes = Intake.all
  end

  # GET /intakes/1
  # GET /intakes/1.json
  def show; end

  # GET /intakes/new
  def new
    @intake = Intake.new
  end

  # POST /intakes
  # POST /intakes.json
  def create
    @intake = Intake.new(intake_params)

    respond_to do |format|
      if @intake.save
        IntakeMailer.with(intake: @intake).triage_email.deliver_later
        format.html { redirect_to @intake, notice: 'Intake was successfully created.' }
        format.json { render :show, status: :created, location: @intake }
      else
        format.html { render :new }
        format.json { render json: @intake.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_intake
    @intake = Intake.find(params[:id])
  end

  def intake_params
    params.require(:intake).permit(:name, :message, :email)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/helpers/admin/cases_helper.rb
module Admin::CasesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intakes_helper.rb
module IntakesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <%= link_to rails_blob_url(blob) do %>
      <% if caption = blob.try(:caption) %>
        <%= caption %>
      <% else %>
        <span class="attachment__name"><%= blob.filename %></span>
        <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
      <% end %>
    <% end %>
  </figcaption>
</figure>

app/views/admin/cases/_form.html.erb
<%= simple_form_for(@admin_case) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/cases/edit.html.erb
<h1>Editing Admin Case</h1>

<%= render 'form', admin_case: @admin_case %>

<%= link_to 'Show', @admin_case %> |
<%= link_to 'Back', admin_cases_path %>

app/views/admin/cases/index.html.erb
<h1>Cases</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Case</th>
      <th scope="col">Date</th>
      <th scope="col">Messages</th>
      <th scope="col">Status</th>
      <th colspan="2" scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_cases.each_with_index do |admin_case, idx| %>
      <tr class="status__<%= admin_case.aasm.current_state %>">
        <th scope="row"><%= idx %></th>
        <td><%= admin_case.intake.name %> (<%= admin_case.intake.email %>)</td>
        <td><%= admin_case.created_at %></td>
        <td><%= admin_case.messages.count %></td>
        <td><%= admin_case.aasm.current_state %></td>
        <td><%= link_to 'Show', admin_case %></td>
        <td><%= link_to 'Destroy', admin_case, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/cases/new.html.erb
<h1>New Admin Case</h1>

<%= render 'form', admin_case: @admin_case %>

<%= link_to 'Back', admin_cases_path %>

app/views/admin/cases/show.html.erb
<div class="card mb-3">
  <div class="card-header">
      from: <%= @admin_case.intake.sender %> on: <%= @admin_case.intake.created_at %>
  </div>
  <div class="card-body">
    <p>original message:</p>

    <%= @admin_case.intake.message %>

    <hr/>

    <%= button_to 'close', admin_case_path(@admin_case), method: :delete, class: 'btn btn-primary card-link' %>
  </div>
</div>


<div class="card mb-3">
  <div class="card-header">
    Add a Message
  </div>
  <div class="card-body">
    <%= form_with(model: Admin::Message.new, url: admin_case_messages_path(@admin_case)) do |form| %>
      <div class="field">
        <%= form.rich_text_area :body %>
      </div>
      <div class="field">
        <button type="submit" class="btn btn-success" name="admin_message[direction]", value="out">
          Send To Client
        </button>
        <button type="submit" class="btn btn-success" name="admin_message[direction]", value="internal">
          Save Internal Note
        </button>
      </div>
    <% end %>
  </div>
</div>

<%= render @admin_case.messages %>

app/views/admin/intakes/_intake.html.erb
<div class="card mb-3">
  <div class="card-header">
      from: <%= intake.sender %> on: <%= intake.created_at %>
  </div>
  <div class="card-body">
    <div class="content">
      <p><%= intake.message %></p>
    </div>
  </div>
</div>

app/views/admin/intakes/index.html.erb
<h1>Intakes</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">source</th>
      <th colspan="3" scope="col">actions</th>
    </tr>
  </thead>

  <tbody>
    <% @intakes.each_with_index do |intake, idx| %>
      <tr>
        <td scope="row"><%= idx %>
        <td><%= intake.name %> (<%= intake.email %>)</td>
        <td><%= link_to 'Show', admin_intake_path(intake) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/intakes/show.html.erb
<div class="intake">
  <%= render @intake %>

  <ul class="actions">
    <li><%= link_to 'Back', admin_intakes_path %> </li>
  </ul>
</div>

app/views/admin/messages/_message.html.erb
<div class="card message__<%= message.direction %> mb-3">
  <div class="card-header">
      from: <%= message.sender %> on: <%= message.created_at %>
  </div>
  <div class="card-body">
    <div class="content">
      <p><%= message.body %></p>
    </div>
  </div>
</div>

app/views/intakes/_form.html.erb
<% if intake.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(intake.errors.count, "error") %> prohibited this intake from being saved:</h2>

    <ul>
      <% intake.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for intake do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :message %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/intakes/_intake.html.erb
<div class="card mb-3">
  <div class="card-header">
      from: <%= intake.sender %> on: <%= intake.created_at %>
  </div>
  <div class="card-body">
    <div class="content">
      <p><%= intake.message %></p>
    </div>
  </div>
</div>

app/views/intakes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Intakes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @intakes.each do |intake| %>
      <tr>
        <td>from: <%= intake.email %></td>
        <td><%= link_to 'Show', intake %></td>
        <td><%= link_to 'Edit', edit_intake_path(intake) %></td>
        <td><%= link_to 'Destroy', intake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intake', new_intake_path %>

app/views/intakes/new.html.erb
<h1>New Intake</h1>

<%= render 'form', intake: Intake.new %>

app/views/intakes/show.html.erb
<%= render @intake %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact Us!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class=container>
      <nav class="nav justify-content-end">
        <!-- active and disabled are also possible classes -->
        <%= link_to "contact us!", new_intake_path, class: 'nav-link' %>
        <% if admin_user_signed_in? %>
          <%= link_to "intakes", admin_intakes_path, class: 'nav-link' %>
          <%= link_to "cases", admin_cases_path, class: 'nav-link' %>
          <%= link_to "sign out", destroy_admin_user_session_path, class: 'nav-link' %>
        <% else %>
          <%= link_to "sign in", new_admin_user_session_path, class: 'nav-link' %>
        <% end %>
      </nav>
      <% if flash.alert %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= flash.alert %>

          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <% if flash.notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= flash.notice %>

          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Welcome!</h5> <p class="card-text">This exercise is
    an excuse to build a minimal case management system, to see whether or not
    it's worth creating the generic case. Want to participate?</p>
    <%= link_to "Contact Us!", new_intake_path, class: 'btn btn-primary' %>
  </div>
</div>